# serverless.yml

service: my-lambda-demo

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 128
  stage: dev
  region: ap-south-1

functions:
  lambda-demo:
    handler: src/index.handler
    events:
      - httpApi: ANY /
      - httpApi: "ANY /{proxy+}"
